MBL_UBOOT_CMD_FILENAME ?= "boot.cmd"

MBL_FIT_BIN_FILENAME ?= "boot.scr"

MBL_KEYSTORE_DIR ?= "${DEPLOY_DIR_IMAGE}"
UBOOT_SIGN_KEYDIR = "${MBL_KEYSTORE_DIR}"

MBL_FIT_ROT_KEY_FILENAME ?= "mblkey"
UBOOT_SIGN_KEYNAME = "${MBL_FIT_ROT_KEY_FILENAME}"
